name: ci

on:
  push:
    branches:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        config:
          - deno-version: 2.0.4

          - deno-version: 2.0.0

          - deno-version: 1.46.3

    name: Deno ${{ matrix.config.deno-version }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.config.deno-version }}

      - name: Legacy
        if: startsWith(matrix.config.deno-version, '1.')
        run: rm deno.lock

      - name: Test
        run: deno task test

      - name: Coverage
        run: deno coverage

  check:
    name: Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.0.4

      - name: Docs
        run: deno task docs

      - name: Artifact docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs

      - name: Linted
        run: deno task linted

      - name: Formatted
        run: deno task formatted

      - name: Publishable
        run: deno task publishable

  npm:
    name: npm

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.0.4

      - name: Build npm prod
        run: deno task npm prod

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Artifact prod
        uses: actions/upload-artifact@v4
        with:
          name: npm-prod
          path: |
            npm
            !npm/node_modules

      - name: Check Publish
        working-directory: npm
        run: npm publish --dry-run

      - name: Build npm dev
        run: deno task npm dev

      - name: Artifact dev
        uses: actions/upload-artifact@v4
        with:
          name: npm-dev
          path: |
            npm
            !npm/node_modules
