name: ci

on:
  push:
    branches:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        config:
          - deno-version: 2.0.4

    name: Deno ${{ matrix.config.deno-version }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.config.deno-version }}

      - name: Test
        run: deno task test
